name: Site Deploy

# on:
#   push:
#     branches:
#       - main
#   # deploy every midnight
#   schedule:
#     - cron: '0 0 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - name: cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        # re `--legacy-peer-deps`, see
        # https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#updating-community-plugins
        run: npm --legacy-peer-deps install
      - name: build with Gatsby
        run: npx gatsby build
      - name: Deploy to GH Pages
        if: github.repository == 'StreamOfJava/streamofjava.github.io'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
